# 어린이집 total 데이터 형성

In [2]:
import pandas as pd
import re
from datetime import datetime
import os

In [388]:
pd.options.display.float_format = '{:.5f}'.format

In [7]:
# 상위 디렉토리의 경로를 만듦
parent_directory = os.path.dirname(os.getcwd())

# CSV 파일 불러오기
nursery_seoul = pd.read_csv(os.path.join(parent_directory, 'data', '서울시 어린이집 정보(표준 데이터).csv'), encoding='cp949')
nursery_score = pd.read_csv(os.path.join(parent_directory, 'data', '어린이집평가 데이터_주소포함.csv'), encoding='UTF8')

# 어린이집 정보 데이터

In [390]:
nursery_seoul.columns

Index(['시군구명', '어린이집코드', '어린이집명', '어린이집유형', '운영현황', '우편번호', '상세주소', '전화번호',
       '팩스번호', '홈페이지주소', '보육실수', '보육실 면적', '놀이터수', 'CCTV총설치수', '보육교직원수', '정원',
       '현원', '시설 위도(좌표값)', '시설 경도(좌표값)', '통학차량운영여부', '인가일자', '휴지시작일자',
       '휴지종료일자', '폐지일자', '데이터기준일자', '제공서비스', '반수-만0세', '반수-만1세', '반수-만2세',
       '반수-만3세', '반수-만4세', '반수-만5세', '반수-영아혼합(만0~2세)', '반수-유아혼합(만3~5세)',
       '반수-특수장애', '반수-총계', '아동수-만0세', '아동수-만1세', '아동수-만2세', '아동수-만3세',
       '아동수-만4세', '아동수-만5세', '아동수-영아혼합(만0~2세)', '아동수-유아혼합(만3~5세)', '아동수-특수장애',
       '아동수-총계', '근속년수-1년미만', '근속년수-1년이상~2년미만', '근속년수-2년이상~4년미만',
       '근속년수-4년이상~6년미만', '근속년수-6년이상', '교직원현황-원장', '교직원현황-보육교사', '교직원현황-특수교사',
       '교직원현황-치료교사', '교직원현황-영양사', '교직원현황-간호사', '교직원현황-간호조무사', '교직원현황-조리원',
       '교직원현황-사무직원', '교직원현황-총계', '데이터수집일'],
      dtype='object')

In [391]:
nursery_seoul_total = nursery_seoul[['시군구명', '어린이집코드', '어린이집명', '어린이집유형', '운영현황', '우편번호',
                                      '상세주소', '전화번호', '시설 위도(좌표값)', '시설 경도(좌표값)', '제공서비스']]

In [392]:
# 폐업된 어린이집 제외
nursery_seoul_total = nursery_seoul_total[nursery_seoul_total['운영현황']=='정상'].reset_index(drop=True)
nursery_seoul_total

,시군구명,어린이집코드,어린이집명,어린이집유형,운영현황,우편번호,상세주소,전화번호,시설 위도(좌표값),시설 경도(좌표값),제공서비스
0,서대문구,11410000379,사랑별어린이집,국공립,정상,3712.00000,서울특별시 서대문구 수색로2길 19-7 DMC금호리첸시아아파트 단지 내,NaN,37.56647,126.97796,일반
1,중구,11140000123,현대캐피탈 도담어린이집,직장,정상,4527.00000,서울특별시 중구 세종대로 14 그랜드센트럴 2층 현대캐피탈 도담어린이집,02-6411-6191,37.55771,126.97456,일반
2,광진구,11215000364,광진구육아종합지원센터(꾸미팡팡공동육아방 3호점),국공립,정상,4999.00000,서울특별시 광진구 동일로56가길 31 3층,02-466-1827,NaN,NaN,시간제보육
3,영등포구,11560000498,삼환어린이집,국공립,정상,7227.00000,서울특별시 영등포구 영중로 145 영등포삼환아파트 104동 101호,02-2679-5967,37.52965,126.90472,일반
4,구로구,11530000648,별숲어린이집,국공립,정상,8226.00000,서울특별시 구로구 경인로43길 49 고척아이파크MD 내 관리실,02-860-0000,37.56647,126.97796,야간연장
...,...,...,...,...,...,...,...,...,...,...,...
4743,동대문구,11230000503,꿈자람공동육아방 배봉산점,국공립,정상,2508.00000,서울특별시 동대문구 전농로16길 97 숲속도서관 1층,02-2212-1975,NaN,NaN,시간제보육
4744,동대문구,11230000500,꿈자람공동육아방 장안1호점,국공립,정상,2624.00000,서울특별시 동대문구 답십리로66길 3,02-2212-0833,NaN,NaN,시간제보육
4745,동대문구,11230000502,꿈자람공동육아방 용신점,국공립,정상,2587.00000,서울특별시 동대문구 무학로 89 2층,02-921-5801,NaN,NaN,시간제보육
4746,동대문구,11230000501,꿈자람공동육아방 장안2호점,국공립,정상,2529.00000,서울특별시 동대문구 한천로28길 9 202동1호,02-2212-5844,NaN,NaN,시간제보육
4747,동대문구,11230000497,육아종합지원센터 제기점,국공립,정상,2476.00000,서울특별시 동대문구 약령시로7길 19,02-923-2272,NaN,NaN,시간제보육

In [393]:
nursery_seoul_total.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4748 entries, 0 to 4747
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   시군구명        4748 non-null   object
 1   어린이집코드      4748 non-null   int64
 2   어린이집명       4748 non-null   object
 3   어린이집유형      4748 non-null   object
 4   운영현황        4748 non-null   object
 5   우편번호        4741 non-null   float64
 6   상세주소        4741 non-null   object
 7   전화번호        4746 non-null   object
 8   시설 위도(좌표값)  4636 non-null   float64
 9   시설 경도(좌표값)  4636 non-null   float64
 10  제공서비스       4748 non-null   object
dtypes: float64(3), int64(1), object(7)
memory usage: 408.2+ KB

In [394]:
# 우편번호 결측치 행 확인
nursery_seoul_total[nursery_seoul_total['우편번호'].isnull()]

,시군구명,어린이집코드,어린이집명,어린이집유형,운영현황,우편번호,상세주소,전화번호,시설 위도(좌표값),시설 경도(좌표값),제공서비스
2880,성동구,11200000402,성수영유아플라자,국공립,정상,NaN,NaN,02-499-5675,NaN,NaN,시간제보육
2881,성동구,11200000399,성동구육아종합지원센터,국공립,정상,NaN,NaN,02-499-5675,NaN,NaN,시간제보육
2882,성동구,11200000401,금호키즈카페 금호장난감세상,국공립,정상,NaN,NaN,02-499-5675,NaN,NaN,시간제보육
2883,성동구,11200000405,옥수장난감세상,국공립,정상,NaN,NaN,02-499-5675,NaN,NaN,시간제보육
2884,성동구,11200000404,왕십리장난감세상,국공립,정상,NaN,NaN,02-499-5675,NaN,NaN,시간제보육
2885,성동구,11200000403,뮤직키즈스튜디오,국공립,정상,NaN,NaN,02-499-5675,NaN,NaN,시간제보육
2886,성동구,11200000400,무지개장난감세상노올터,국공립,정상,NaN,NaN,02-499-5675,NaN,NaN,시간제보육

In [395]:
# 우편번호 결측치 행 제거
nursery_seoul_total = nursery_seoul_total.dropna(subset='우편번호', axis=0)
nursery_seoul_total[nursery_seoul_total['우편번호'].isnull()]

Empty DataFrame
Columns: [시군구명, 어린이집코드, 어린이집명, 어린이집유형, 운영현황, 우편번호, 상세주소, 전화번호, 시설 위도(좌표값), 시설 경도(좌표값), 제공서비스]
Index: []

In [396]:
# 우편번호 타입 변경
nursery_seoul_total['우편번호'] = nursery_seoul_total['우편번호'].astype(int)

/var/folders/ct/39sw_n0j54qf99r5l8vpgdcm0000gn/T/ipykernel_99356/3205470666.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nursery_seoul_total['우편번호'] = nursery_seoul_total['우편번호'].astype(int)

In [397]:
nursery_seoul_total['어린이집코드'].nunique()

4741

# 어린이집 평가 데이터 전처리

In [398]:
nursery_score = nursery_score.drop(columns='Unnamed: 0', axis=1)

In [399]:
nursery_score['어린이집명'].nunique()

3179

In [400]:
# 주소에서 우편번호 분리
nursery_score['우편번호'] = nursery_score['주소'].apply(lambda x: re.findall(r'\d+', x)[0])
# 타입 변경
nursery_score['우편번호'] = nursery_score['우편번호'].astype(int)

In [401]:
nursery_score.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4011 entries, 0 to 4010
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   구            4011 non-null   object
 1   주소           4011 non-null   object
 2   어린이집명        4011 non-null   object
 3   어린이집등급       4011 non-null   object
 4   보육과정 및 상호작용  4009 non-null   object
 5   보육환경 및 운영관리  4009 non-null   object
 6   건강 및 안전      4009 non-null   object
 7   교직원          4009 non-null   object
 8   평가 인증 년월     4007 non-null   float64
 9   우편번호         4011 non-null   int64
dtypes: float64(1), int64(1), object(8)
memory usage: 313.5+ KB

# 어린이집 기본정보, 평가 merge

In [402]:
total = pd.merge(nursery_score, nursery_seoul_total, how='inner')
len(total)

3908

In [403]:
# 어린이집코드를 기준으로 중복행 확인
total[total.duplicated(subset='어린이집코드', keep=False)]

Empty DataFrame
Columns: [구, 주소, 어린이집명, 어린이집등급, 보육과정 및 상호작용, 보육환경 및 운영관리, 건강 및 안전, 교직원, 평가 인증 년월, 우편번호, 시군구명, 어린이집코드, 어린이집유형, 운영현황, 상세주소, 전화번호, 시설 위도(좌표값), 시설 경도(좌표값), 제공서비스]
Index: []

In [404]:
total.head()

,구,주소,어린이집명,어린이집등급,보육과정 및 상호작용,보육환경 및 운영관리,건강 및 안전,교직원,평가 인증 년월,우편번호,시군구명,어린이집코드,어린이집유형,운영현황,상세주소,전화번호,시설 위도(좌표값),시설 경도(좌표값),제공서비스
0,종로구,(03159) 서울특별시 종로구 종로 33 그랑서울 타워2 (2층),GS건설 꿈과 희망의 어린이집,A,우수,우수,우수,우수,2022.09000,3159,종로구,11110000156,직장,정상,서울특별시 종로구 종로 33 그랑서울 타워2 (2층),02-3789-5971,37.57096,126.98144,일반
1,종로구,(03175) 서울특별시 종로구 신문로2가 경희궁길 26 썬타워빌딩 1층,KIM&CHANG 어린이집,A,우수,우수,우수,우수,2023.08000,3175,종로구,11110000150,직장,정상,서울특별시 종로구 신문로2가 경희궁길 26 썬타워빌딩 1층,02-738-6901,37.57227,126.97099,일반
2,종로구,(03082) 서울특별시 종로구 대학로 65 (연건동),KT혜화 어린이집,A,우수,우수,우수,우수,2023.11000,3082,종로구,11110000111,직장,정상,서울특별시 종로구 대학로 65 (연건동),02-3676-9300,37.57700,127.00427,일반
3,종로구,(03184) 서울특별시 종로구 신문로2가 새문안로 58,LG광화문어린이집,A,우수,우수,우수,우수,2019.10000,3184,종로구,11110000157,직장,정상,서울특별시 종로구 신문로2가 새문안로 58,070-4065-0286,37.56928,126.97158,일반
4,종로구,(03160) 서울특별시 종로구 종로 47,SC으뜸별 어린이집,B,우수,보통,우수,우수,2020.01000,3160,종로구,11110000170,직장,정상,서울특별시 종로구 종로 47,02-3210-0904,37.57113,126.98244,일반

In [405]:
# 불필요한 열 제거
total = total.drop(columns=['구', '주소', '운영현황'], axis=1)
total.head()

,어린이집명,어린이집등급,보육과정 및 상호작용,보육환경 및 운영관리,건강 및 안전,교직원,평가 인증 년월,우편번호,시군구명,어린이집코드,어린이집유형,상세주소,전화번호,시설 위도(좌표값),시설 경도(좌표값),제공서비스
0,GS건설 꿈과 희망의 어린이집,A,우수,우수,우수,우수,2022.09000,3159,종로구,11110000156,직장,서울특별시 종로구 종로 33 그랑서울 타워2 (2층),02-3789-5971,37.57096,126.98144,일반
1,KIM&CHANG 어린이집,A,우수,우수,우수,우수,2023.08000,3175,종로구,11110000150,직장,서울특별시 종로구 신문로2가 경희궁길 26 썬타워빌딩 1층,02-738-6901,37.57227,126.97099,일반
2,KT혜화 어린이집,A,우수,우수,우수,우수,2023.11000,3082,종로구,11110000111,직장,서울특별시 종로구 대학로 65 (연건동),02-3676-9300,37.57700,127.00427,일반
3,LG광화문어린이집,A,우수,우수,우수,우수,2019.10000,3184,종로구,11110000157,직장,서울특별시 종로구 신문로2가 새문안로 58,070-4065-0286,37.56928,126.97158,일반
4,SC으뜸별 어린이집,B,우수,보통,우수,우수,2020.01000,3160,종로구,11110000170,직장,서울특별시 종로구 종로 47,02-3210-0904,37.57113,126.98244,일반

In [406]:
# 타입 확인
total.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3908 entries, 0 to 3907
Data columns (total 16 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   어린이집명        3908 non-null   object
 1   어린이집등급       3908 non-null   object
 2   보육과정 및 상호작용  3907 non-null   object
 3   보육환경 및 운영관리  3907 non-null   object
 4   건강 및 안전      3907 non-null   object
 5   교직원          3907 non-null   object
 6   평가 인증 년월     3904 non-null   float64
 7   우편번호         3908 non-null   int64
 8   시군구명         3908 non-null   object
 9   어린이집코드       3908 non-null   int64
 10  어린이집유형       3908 non-null   object
 11  상세주소         3908 non-null   object
 12  전화번호         3908 non-null   object
 13  시설 위도(좌표값)   3908 non-null   float64
 14  시설 경도(좌표값)   3908 non-null   float64
 15  제공서비스        3908 non-null   object
dtypes: float64(3), int64(2), object(11)
memory usage: 519.0+ KB

In [407]:
# 평가가 없는 데이터 제거
total = total.dropna(subset=['어린이집등급', '보육과정 및 상호작용', '보육환경 및 운영관리', '건강 및 안전', '교직원', ], axis=0)
total[total['교직원'].isnull()]

Empty DataFrame
Columns: [어린이집명, 어린이집등급, 보육과정 및 상호작용, 보육환경 및 운영관리, 건강 및 안전, 교직원, 평가 인증 년월, 우편번호, 시군구명, 어린이집코드, 어린이집유형, 상세주소, 전화번호, 시설 위도(좌표값), 시설 경도(좌표값), 제공서비스]
Index: []

In [408]:
# 우편번호 결측치 행 제거
total = total.dropna(subset='평가 인증 년월', axis=0)
total[total['평가 인증 년월'].isnull()]

Empty DataFrame
Columns: [어린이집명, 어린이집등급, 보육과정 및 상호작용, 보육환경 및 운영관리, 건강 및 안전, 교직원, 평가 인증 년월, 우편번호, 시군구명, 어린이집코드, 어린이집유형, 상세주소, 전화번호, 시설 위도(좌표값), 시설 경도(좌표값), 제공서비스]
Index: []

In [409]:
# 평가 인증 년월 datetime으로 타입 변경
total['평가 인증 년월'] = total['평가 인증 년월'].astype(str)
total['평가 인증 년월'] = total['평가 인증 년월'].apply(lambda x : x.replace('.', ''))
total['평가 인증 년월'] = total['평가 인증 년월'].apply(lambda _ : datetime.strptime(_,'%Y%m'))

In [410]:
total.info() # 중복행, 결측치 행 제거, 타입변경 결과 확인

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3903 entries, 0 to 3907
Data columns (total 16 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   어린이집명        3903 non-null   object
 1   어린이집등급       3903 non-null   object
 2   보육과정 및 상호작용  3903 non-null   object
 3   보육환경 및 운영관리  3903 non-null   object
 4   건강 및 안전      3903 non-null   object
 5   교직원          3903 non-null   object
 6   평가 인증 년월     3903 non-null   datetime64[ns]
 7   우편번호         3903 non-null   int64
 8   시군구명         3903 non-null   object
 9   어린이집코드       3903 non-null   int64
 10  어린이집유형       3903 non-null   object
 11  상세주소         3903 non-null   object
 12  전화번호         3903 non-null   object
 13  시설 위도(좌표값)   3903 non-null   float64
 14  시설 경도(좌표값)   3903 non-null   float64
 15  제공서비스        3903 non-null   object
dtypes: datetime64[ns](1), float64(2), int64(2), object(11)
memory usage: 518.4+ KB

In [414]:
# 최종데이터
total.head()

,어린이집명,어린이집등급,보육과정 및 상호작용,보육환경 및 운영관리,건강 및 안전,교직원,평가 인증 년월,우편번호,시군구명,어린이집코드,어린이집유형,상세주소,전화번호,시설 위도(좌표값),시설 경도(좌표값),제공서비스
0,GS건설 꿈과 희망의 어린이집,A,우수,우수,우수,우수,2022-09-01,3159,종로구,11110000156,직장,서울특별시 종로구 종로 33 그랑서울 타워2 (2층),02-3789-5971,37.57096,126.98144,일반
1,KIM&CHANG 어린이집,A,우수,우수,우수,우수,2023-08-01,3175,종로구,11110000150,직장,서울특별시 종로구 신문로2가 경희궁길 26 썬타워빌딩 1층,02-738-6901,37.57227,126.97099,일반
2,KT혜화 어린이집,A,우수,우수,우수,우수,2023-11-01,3082,종로구,11110000111,직장,서울특별시 종로구 대학로 65 (연건동),02-3676-9300,37.57700,127.00427,일반
3,LG광화문어린이집,A,우수,우수,우수,우수,2019-01-01,3184,종로구,11110000157,직장,서울특별시 종로구 신문로2가 새문안로 58,070-4065-0286,37.56928,126.97158,일반
4,SC으뜸별 어린이집,B,우수,보통,우수,우수,2020-01-01,3160,종로구,11110000170,직장,서울특별시 종로구 종로 47,02-3210-0904,37.57113,126.98244,일반

In [415]:
# total.to_csv('./data/어린이집_total.csv', index=False, encoding='cp949')